// Code generated by 'invalid -types=NewReq' in 2022-06-08 06:29:52.499; DO NOT EDIT.

package demo

import (
	"errors"
)

func (i *NewReq) Invalid() (err error) {
	for _, v := range []func() error{
		i._Score_invalid_,
	} {
		if err = v(); err != nil {
			return err
		}
	}

	return
}

// 规则：<!nil; !20; [1,)>
func (i *NewReq) _Score_invalid_() (err error) {
	// !nil
	if i.Score == nil {
		err = errors.New(`invalid<not>: NewReq.Score must not be nil`)
		return
	}
	// !20
	if i.Score != nil && *i.Score == 20 {
		err = errors.New(`invalid<not>: NewReq.Score must not be 20`)
		return
	}
	if i.Score == nil {
		return nil
	}
	if *i.Score < 1 {
		return errors.New("invalid<range>: NewReq.Score must not be less than 1")
	}

	return
}
