// Code generated by 'invalid ' in 2022-06-08 10:12:17.752; DO NOT EDIT.

package demo

import (
	"errors"
	"regexp"
	"time"
)

var (
	regex_pill_22      *regexp.Regexp
	time_pill_left_23  time.Time
	time_pill_right_23 time.Time
)

func init() {
	var err error

	regex_pill_22, err = regexp.Compile("^A")
	if err != nil {
		panic(err)
	}

	time_pill_left_23, err = time.Parse("2006", "2006")
	if err != nil {
		panic(err)
	}

	time_pill_right_23, err = time.Parse("2006", "2007")
	if err != nil {
		panic(err)
	}

}

func (i *Pill) Invalid() (err error) {
	for _, v := range []func() error{
		i._ID_invalid_,
		i._Socre_invalid_,
		i._SocreSlice_invalid_,
		i._SocreSlicePtr_invalid_,
		i._IDSlice_invalid_,
		i._IDSlicePtr_invalid_,
		i._Not_invalid_,
		i._NotPtr_invalid_,
		i._NotSlice_invalid_,
		i._NotSlicePtr_invalid_,
		i._Name_invalid_,
		i._Time_invalid_,
	} {
		if err = v(); err != nil {
			return err
		}
	}

	return
}

// 规则：<!nil; !2; d3>
func (i *Pill) _ID_invalid_() (err error) {
	defer func() {
		if err != nil {
			// d3
			var tmp int64 = 3
			i.ID = &tmp
			err = nil
		}
	}()
	// !nil
	if i.ID == nil {
		err = errors.New(`invalid<not>: Pill.ID must not be nil`)
		return
	}
	// !2
	if i.ID != nil && *i.ID == 2 {
		err = errors.New(`invalid<not>: Pill.ID must not be 2`)
		return
	}

	return
}

// 规则：<d12; v>
func (i *Pill) _Socre_invalid_() (err error) {
	defer func() {
		if err != nil {
			// d12
			var tmp PInt = 12
			i.Socre = &tmp
			err = nil
		}
	}()
	// v
	err = i.Socre.Invalid()
	if err != nil {
		return err
	}

	return
}

// 规则：<v; [2,3)>
func (i *Pill) _SocreSlice_invalid_() (err error) {
	// v
	for idx := range i.SocreSlice {
		err = i.SocreSlice[idx].Invalid()
		if err != nil {
			return
		}
	}
	for idx := range i.SocreSlice {
		if i.SocreSlice[idx] < 2 {
			err = errors.New(`invalid<range>: each of Pill.SocreSlice must be greater than or equal to 2")`)
			return
		}
	}
	for idx := range i.SocreSlice {
		if i.SocreSlice[idx] >= 3 {
			err = errors.New(`invalid<range>: each of Pill.SocreSlice must be less than 3")`)
			return
		}
	}

	return
}

// 规则：<v; (3, 4]>
func (i *Pill) _SocreSlicePtr_invalid_() (err error) {
	// v
	for idx := range *(i.SocreSlicePtr) {
		err = (*i.SocreSlicePtr)[idx].Invalid()
		if err != nil {
			return
		}
	}
	if i.SocreSlicePtr != nil {
		for idx := range *i.SocreSlicePtr {
			if (*i.SocreSlicePtr)[idx] <= 3 {
				err = errors.New(`invalid<range>: each of Pill.SocreSlicePtr must be greater than 3")`)
				return
			}
		}
	}
	if i.SocreSlicePtr != nil {
		for idx := range *i.SocreSlicePtr {
			if (*i.SocreSlicePtr)[idx] > 4 {
				err = errors.New(`invalid<range>: each of Pill.SocreSlicePtr must be less than or equal to 4")`)
				return
			}
		}
	}

	return
}

// 规则：<{1, 3, 4, i.IDFloat64}; dmake([]float64, 0, 10); l[1,)>
func (i *Pill) _IDSlice_invalid_() (err error) {
	defer func() {
		if err != nil {
			// dmake([]float64, 0, 10)
			i.IDSlice = make([]float64, 0, 10)
			err = nil
		}
	}()
	// {1, 3, 4, i.IDFloat64}
	tot_9 := 0 // 符合枚举值的总数
	for idx := range i.IDSlice {
		for _, v := range []float64{1, 3, 4, i.IDFloat64} {
			if i.IDSlice[idx] == v {
				tot_9++
				break
			}
		}
	}
	if tot_9 != len(i.IDSlice) {
		err = errors.New(`invalid<enum>: each of Pill.IDSlice must be in the {1, 3, 4, i.IDFloat64}`)
		return
	}
	if len(i.IDSlice) < 1 {
		err = errors.New(`invalid<range>: the length of Pill.IDSlice must be greater than or equal to 1")`)
		return
	}

	return
}

// 规则：<{1, 3, 4}; l(2,2)>
func (i *Pill) _IDSlicePtr_invalid_() (err error) {
	// {1, 3, 4}
	if i.IDSlicePtr != nil {
		tot_12 := 0 // 符合枚举值的总数
		for _, val := range *(i.IDSlicePtr) {
			for _, v := range []float32{1, 3, 4} {
				if val == v {
					tot_12++
					break
				}
			}
		}
		if tot_12 != len(*(i.IDSlicePtr)) {
			err = errors.New(`invalid<enum>: each of Pill.IDSlicePtr must be in the {1, 3, 4}`)
			return
		}
	}
	if len(*i.IDSlicePtr) <= 2 {
		err = errors.New(`invalid<range>: the length of Pill.IDSlicePtr must be greater than 2")`)
		return
	}
	if len(*i.IDSlicePtr) >= 2 {
		err = errors.New(`invalid<range>: the length of Pill.IDSlicePtr must be less than 2")`)
		return
	}

	return
}

// 规则：<!2; !i.IDInt>
func (i *Pill) _Not_invalid_() (err error) {
	// !2
	if i.Not == 2 {
		err = errors.New(`invalid<not>: Pill.Not must not be 2`)
		return
	}
	// !i.IDInt
	if i.Not == i.IDInt {
		err = errors.New(`invalid<not>: Pill.Not must not be i.IDInt`)
		return
	}

	return
}

// 规则：<!2; !nil>
func (i *Pill) _NotPtr_invalid_() (err error) {
	// !2
	if i.NotPtr != nil && *i.NotPtr == 2 {
		err = errors.New(`invalid<not>: Pill.NotPtr must not be 2`)
		return
	}
	// !nil
	if i.NotPtr == nil {
		err = errors.New(`invalid<not>: Pill.NotPtr must not be nil`)
		return
	}

	return
}

// 规则：<!2>
func (i *Pill) _NotSlice_invalid_() (err error) {
	// !2
	for idx := range i.NotSlice {
		if i.NotSlice[idx] == 2 {
			err = errors.New(`invalid<not>: each of Pill.NotSlice must not be 2`)
			return
		}
	}

	return
}

// 规则：<!nil; !4>
func (i *Pill) _NotSlicePtr_invalid_() (err error) {
	// !nil
	if i.NotSlicePtr == nil {
		err = errors.New(`invalid<not>: Pill.NotSlicePtr must not be nil`)
		return
	}
	// !4
	if i.NotSlicePtr != nil {
		for _, val := range *(i.NotSlicePtr) {
			if val == 4 {
				err = errors.New(`invalid<not>: each of Pill.NotSlicePtr must not be 4`)
				return
			}
		}
	}

	return
}

// 规则：<!""; r"^A">
func (i *Pill) _Name_invalid_() (err error) {
	// !""
	if i.Name == "" {
		err = errors.New(`invalid<not>: Pill.Name must not be ""`)
		return
	}
	// r"^A"
	if !regex_pill_22.MatchString(i.Name) {
		err = errors.New(`invalid<regex>: Pill.Name must conform to the regex<"^A">`)
		return
	}

	return
}

// 规则：<["2006", "2006", "2007")>
func (i *Pill) _Time_invalid_() (err error) {
	var time_Time_left time.Time
	time_Time_left, err = time.Parse("2006", i.Time)
	if err != nil {
		err = errors.New(`invalid<range>: Pill.Time can not be parse to time`)
		return
	}
	if time_Time_left.UnixMicro() >= time_pill_left_23.UnixMicro() {
		err = errors.New(`invalid<range>: Pill.Time must be less than "2007")`)
		return
	}
	var time_Time_right time.Time
	time_Time_right, err = time.Parse("2006", i.Time)
	if err != nil {
		err = errors.New(`invalid<range>: Pill.Time can not be parse to time`)
		return
	}
	if time_Time_right.UnixMicro() >= time_pill_right_23.UnixMicro() {
		err = errors.New(`invalid<range>: Pill.Time must be less than "2007")`)
		return
	}

	return
}
