package generate

import (
	"bytes"
	"fmt"
	"go/ast"
	"go/format"
	"invalid/internal/model"
	"io/ioutil"
	"log"
	"os"
	"strings"
	"time"

	"golang.org/x/tools/go/packages"
)

type Generator struct {
	buf bytes.Buffer // Accumulated output.
	pkg *Package     // Package we are scanning.

	val []*model.Struct
}

// AddPackage adds a type checked Package and its syntax files to the generator.
func (g *Generator) AddPackage(pkg *packages.Package) {
	g.pkg = &Package{
		Name:  pkg.Name,
		Defs:  pkg.TypesInfo.Defs,
		Files: make([]*File, len(pkg.Syntax)),
	}

	for i, file := range pkg.Syntax {
		g.pkg.Files[i] = &File{
			File: file,
			Pkg:  g.pkg,
		}
	}
}

// ParsePackage
//	ParsePackage analyzes the single package constructed from the patterns and tags.
//	ParsePackage exits if there is an error.
//	ParsePackage 分析由模式和标签构造的单个包。
//	如果出现错误，ParsePackage 退出
func (g *Generator) ParsePackage(patterns []string, tags []string) {
	cfg := &packages.Config{
		Mode:       mode,
		Tests:      false, // 不应当支持测试文件
		BuildFlags: []string{fmt.Sprintf("-tags=%s", strings.Join(tags, " "))},
	}
	pkgs, err := packages.Load(cfg, patterns...)
	if err != nil {
		log.Fatal(err)
	}
	if len(pkgs) != 1 {
		log.Fatalf("error: %d packages found", len(pkgs))
	}

	g.AddPackage(pkgs[0])
}

func (g *Generator) Printf(format string, a ...any) {
	fmt.Fprintf(&g.buf, format, a...)
}

// 解析对应结构体
func (g *Generator) Parse(targetName string) {
	for _, file := range g.pkg.Files {
		if file.File != nil {
			for k, v := range file.File.Scope.Objects {
				if k == targetName {
					typeSpec, ok := v.Decl.(*ast.TypeSpec)
					if !ok {
						log.Panicf("key<%s>, value<%#+v>, value.Decl must be *ast.TypeSpec", k, v)
					}

					structType, ok := typeSpec.Type.(*ast.StructType)
					if !ok {
						log.Panicf("vv.Type<%#v> must be *ast.StructType", typeSpec.Type)
					}

					g.val = append(g.val, model.NewStruct(g.pkg.Name, targetName, structType))

					return
				}
			}
		}
	}
	log.Panicf("can not find the struct named<%s>", targetName)
}

// 写入代码
func (g *Generator) Generate() {
	g.Printf("// Code generated by 'invalid %s' in %s; DO NOT EDIT.\n\n",
		strings.Join(os.Args[1:], " "), time.Now().Format("2006-01-02 15:04:05.999"))
	g.Printf("package %s", g.pkg.Name)
	g.Printf("\n")

	vals := map[string]string{}
	pkgs := map[string]struct{}{}
	meths := ""
	for _, val := range g.val {
		for k, v := range val.Val {
			vals[k] = v
		}
		for k, v := range val.Pkgs {
			pkgs[k] = v
		}
		meths += val.Meths()
	}

	if len(pkgs) > 0 {
		g.Printf("import (")
		for k := range pkgs {
			g.Printf(`"%s"`, k)
			g.Printf("\n")
		}
		g.Printf(")\n\n")
	}

	log.Println(vals)
	log.Println(pkgs)

	if len(vals) > 0 {
		defineStr := ""
		assignStr := ""
		existErr := false
		model.SortMap(vals, func(k, v string) {
			defineStr += k + "\n"
			assignStr += v + "\n"
			if strings.Contains(v, ", err =") {
				existErr = true
			}
		})
		if existErr {
			assignStr = "var err error\n\n" + assignStr
		}

		g.Printf("var (")
		g.Printf(defineStr)
		g.Printf(")\n\n")

		g.Printf("func init() {")
		g.Printf(assignStr)
		g.Printf("}\n\n")
	}

	g.Printf(meths)
}

// 保存到指定文件
func (g *Generator) Save(structName string) {
	fileName := fmt.Sprintf("%s_invalid.go", strings.ToLower(structName))

	var err error
	var src []byte
	src, err = format.Source(g.buf.Bytes())
	if err != nil {
		log.Printf("warning: internal error: invalid Go generated: %s", err)
		log.Printf("warning: compile the package to analyze the error")
		src = g.buf.Bytes()
	}

	err = ioutil.WriteFile(fileName, src, 0666)
	if err != nil {
		panic(err)
	}
}
